CCACHE		= ccache
CC		= $(CCACHE) gcc -pipe -Wall -Werror -Wno-unused -g
CXX		= $(CCACHE) g++ -pipe -Wall -Werror -Wno-unused -g
FC		= $(CCACHE) gfortran -pipe -Wall -g

ifndef DEBUG
CFLAGS          = -g -O3 -mtune=native -unroll-all-loops -fstrict-aliasing -ftree-loop-distribution
else
CFLAGS          = -pg -O0
endif

CFLAGS          += -DDEBUG -UNDEBUG
CFLAGS		+= -I$(PREFIX)/include -I$(PREFIX)/../common/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__USE_LARGEFILE64 -DBOOST_NO_CWCHAR -DBOOST_NO_CWCTYPE
CXXFLAGS	= $(CFLAGS) -Woverloaded-virtual
FFLAGS		= $(CFLAGS)
LDFLAGS		=
DEPRULE		= $(PREFIX)/Makefile.autodep
AR		= ar

LDFLAGS		+= -lboost_program_options

